{{- if and .Values.database.password (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastschema.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fastschema.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.database.password | b64enc | quote }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastschema.fullname" . }}-app-key
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fastschema.labels" . | nindent 4 }}
type: Opaque
data:
  app-key: {{ if .Values.appKey }}{{ .Values.appKey | b64enc | quote }}{{ else }}{{ randAlphaNum 32 | b64enc | quote }}{{ end }}
